Name: Validate

validate-branch:
    runs-on: ${{ vars.RUNNER }}
    outputs:
      is_valid: ${{ steps.check-branch.outputs.is_valid }}
    steps:
      - name: Validate release branch
        id: check-branch
        run: |
          if [[ "${{ github.event.inputs.release_branch }}" =~ ^release\/.* ]]; then
            echo "is_valid=true" >> $GITHUB_ENV
          else
            echo "is_valid=false" >> $GITHUB_ENV
            echo "::error::The release branch must start with 'release/'"
            exit 1
          fi
          
      - name: Debug validate-branch output
        run: |
          echo "is_valid output: ${{ steps.check-branch.outputs.is_valid }}"