name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Select the release branch'
        required: true
        default: 'release/'        
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - production
          - staging
          - development

jobs: