name: Deploy Release Branch

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Select the release branch'
        required: true
      environment:
        description: 'Select the environment'
        required: true

jobs:
  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}  # User selects the environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_branch }}
