name: Release

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Select the release branch'
        required: true
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - production
          - staging
          - development

jobs:
#  validate-branch:
#    runs-on: ${{ vars.RUNNER }}
#    outputs:
#      is_valid: ${{ steps.check-branch.outputs.is_valid }}
#    steps:
#      - name: Validate release branch
#        id: check-branch
#        run: |
#          if [[ "${GITHUB_EVENT_INPUTS_RELEASE_BRANCH}" =~ ^release\/.* ]]; then
#            echo "is_valid=true" >> $GITHUB_ENV
#          else
#            echo "is_valid=false" >> $GITHUB_ENV
#            echo "::error::The release branch must start with 'release/'"
#           exit 1
#         fi
 
  display-variables:
    name: Check Variables and Secrets
    runs-on: ${{ vars.RUNNER }}
    #needs: validate-branch
    #if: needs.validate-branch.outputs.is_valid == 'true'
    environment: ${{ github.event.inputs.environment }}  # User selects the environment
    steps:
    - name: Show me the money!
      run: |
        echo "Variable: ${{ vars.VARIABLE }}"      
